# makefile.gtdbtk
#
# Library makefile to make it easier to fetch data files for GTDB tk.
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@lnu.se

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
GTDBTK_RELEASE = SET GTDBTK_RELEASE TO THE CURRENT RELEASE (JUST THE NUMBER, E.G. 86)

# Use --cpus N 
GTDBTK_OPTIONS = 

# Use --pplacer_cpus N to set number of cores and likely --skip_ani_screen
GTDBTK_IDENTIFY_OPTIONS =

GTDBTK_DE_NOVO_OPTIONS =

# GTDB-Tk's documentation gives p__Patescibacteriota and p__Altiarchaeota as examples
GTDBTK_DE_NOVO_OUTGROUP = SET GTDBTK_DE_NOVO_OUTGROUP TO SOMETHING SUITABLE
GTDBTK_DE_NOVO_DOMAIN = SET to --archaea OR --bacteria

# *** Targets ***

# Fetch data
gtdbtk_current_data.tar.gz:
	wget https://data.ace.uq.edu.au/public/gtdbtk/release_$(GTDBTK_RELEASE)/gtdbtk.r$(GTDBTK_RELEASE)_data.tar.gz
	ln -s gtdbtk.r$(GTDBTK_RELEASE)_data.tar.gz $@

# Run the standard workflow on a single fna file in the current directory
%.gtdbtk_classify_wf.d: %.fna
	gtdbtk classify_wf --genome_dir $(dir $<) --out_dir $@ $(GTDBTK_OPTIONS) $(GTDBTK_IDENTIFY_OPTIONS)

# Run the standard workflow on all genomes in "genome_bins"
gtdbtk_classify_wf.d: $(wildcard genome_bins/*.fna)
	gtdbtk classify_wf --genome_dir $(dir $<) --out_dir $@ $(GTDBTK_OPTIONS) $(GTDBTK_IDENTIFY_OPTIONS)

# Run the de_novo workflow on all genomes in "genome_bins"
gtdbtk_de_novo_wf.d: $(wildcard genome_bins/*.fna)
	gtdbtk de_novo_wf --genome_dir $(dir $<) --out_dir $@ --outgroup_taxon $(GTDBTK_DE_NOVO_OUTGROUP) $(GTDBTK_DE_NOVO_DOMAIN) $(GTDBTK_OPTIONS) $(GTDBTK_DE_NOVO_OPTIONS)

# All fna files in a directory ending with .bins.d
%.gtdbtk_classify_wf.d: %.bins.d
	gtdbtk classify_wf --genome_dir $< --out_dir $@ $(GTDBTK_OPTIONS) $(GTDBTK_IDENTIFY_OPTIONS)

# Splits the ; separated hierarchy in the original files to a tab separated
%.split.tsv: %.tsv
	sed 's/\td__/\t/' $< | sed 's/;[a-z]__/\t/g' > $@

# Makes a file with unique species lineages, by removing the genome accno and finding the unique
%.uniqlineages.tsv: %.genomes.split.tsv
	cut -f 2-20 $< | sort -u > $@
