# makefile.tara
#
# Library makefile to make fetching sequences from various TARA projects simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@dbb.su.se daniel.lundin@lnu.se

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#

# *** Targets ***

# Eukaryotes
diamond: eukaryote_unigenes.fna.gz eukaryote_taxonomy.tsv.gz eukaryote_pfams.tsv.gz eukaryote_metag_occurrences.tsv.gz eukaryote_metat_occurrences.tsv.gz eukaryote_unigene_clusters_composition.tsv.gz eukaryote_unigene_clusters_properties.tsv.gz

eukaryote_unigenes.fna.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/Geneset-v1/MATOU-v1.fna.gz

eukaryote_taxonomy.tsv.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/Geneset-v1/taxonomy.tsv.gz

eukaryote_pfams.tsv.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/Geneset-v1/pfam.tsv.gz

eukaryote_metag_occurrences.tsv.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/Geneset-v1/metagenomic_occurrences.tsv.gz

eukaryote_metat_occurrences.tsv.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/Geneset-v1/metatranscriptomic_occurrences.tsv.gz

eukaryote_unigene_clusters_composition.tsv.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/Geneset-v1/unigeneID_clusterID.tsv.gz

eukaryote_unigene_clusters_properties.tsv.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/Geneset-v1/clusters.tsv.gz

# Eukaryotic SAGs
eukaryote_SAGs.faa.gz: MAST-3_clade_A.faa.gz MAST-3_clade_F.faa.gz MAST-4_clade_A_1.faa.gz MAST-4_clade_A_2.faa.gz MAST-4_clade_C.faa.gz MAST-4_clade_E.faa.gz
	unpigz -c $^ | pigz -c > $@

MAST-3_clade_A.faa.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/SAG-v1/m3a.faa.gz

MAST-3_clade_F.faa.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/SAG-v1/m3f.faa.gz

MAST-4_clade_A_1.faa.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/SAG-v1/m4a1.faa.gz

MAST-4_clade_A_2.faa.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/SAG-v1/m4a2.faa.gz

MAST-4_clade_C.faa.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/SAG-v1/m4c.faa.gz

MAST-4_clade_E.faa.gz:
	wget -O $@ http://www.genoscope.cns.fr/tara/localdata/data/SAG-v1/m4e.faa.gz


# Delmont et al. 2018 MAGs

# Make this one and the next (delmont2018.non-redudant_mags.fna.gz) to get the
# nucleotides for *each MAG* in a file
delmont2018.non-redundant_mags.tar.gz:
	wget -O $@ https://ndownloader.figshare.com/files/8243654

delmont2018.non-redudant_mags.fna.gz: $(wildcard NON_REDUNDANT_MAGs/TARA_*_MAG_*.fa)
	cat $^ | gzip -c > $@

# This one and the next (delmont2018.all_aa_sequences.faa.gz) gives all amino
# acids in a file
delmont2018.all_aa_sequences.zip:
	wget -O $@ https://ndownloader.figshare.com/articles/4902917/versions/1

delmont2018.all_aa_sequences.faa.gz: $(wildcard TARA_*-AA_sequences.fa.gz)
	rm -f $@
	for f in $^; do \
	  pf=$$(echo $$f | sed 's/-AA_sequences.fa.gz//'); \
	  echo "--> $$f (pf: $$pf) <--"; \
	  unpigz -c $$f | sed "s/^>/>$${pf}_/" | gzip -c >> $@; \
	done

delmont2018.raw_assembly.fna.gz: TARA_ANE_RAW.fa.gz TARA_ANW_RAW.fa.gz TARA_ASE_RAW.fa.gz TARA_ASW_RAW.fa.gz TARA_ION_RAW.fa.gz TARA_IOS_RAW.fa.gz TARA_MED_RAW.fa.gz TARA_PON_RAW.fa.gz TARA_PSE_RAW.fa.gz TARA_PSW_RAW.fa.gz TARA_RED_RAW.fa.gz TARA_SOC_RAW.fa.gz
	unpigz -c $^ | pigz -c > $@

TARA_ANE_RAW.fa.gz:
	wget -O  $@ -c https://ndownloader.figshare.com/files/8243627

TARA_ANW_RAW.fa.gz:
	wget -O  $@ -c https://ndownloader.figshare.com/files/8243633

TARA_ASE_RAW.fa.gz:
	wget -O  $@ -c https://ndownloader.figshare.com/files/8243648

TARA_ASW_RAW.fa.gz:
	wget -O  $@ -c https://ndownloader.figshare.com/files/8243651

TARA_ION_RAW.fa.gz:
	wget -O  $@ -c https://ndownloader.figshare.com/files/8243657

TARA_IOS_RAW.fa.gz:
	wget -O  $@ -c https://ndownloader.figshare.com/files/8243660

TARA_MED_RAW.fa.gz:
	wget -O  $@ -c https://ndownloader.figshare.com/files/8243663

TARA_PON_RAW.fa.gz:
	wget -O  $@ -c https://ndownloader.figshare.com/files/8243666

TARA_PSE_RAW.fa.gz:
	wget -O  $@ -c https://ndownloader.figshare.com/files/8243669

TARA_PSW_RAW.fa.gz:
	wget -O  $@ -c https://ndownloader.figshare.com/files/8243672

TARA_RED_RAW.fa.gz:
	wget -O  $@ -c https://ndownloader.figshare.com/files/8243675

TARA_SOC_RAW.fa.gz:
	wget -O  $@ -c https://ndownloader.figshare.com/files/8243678
