# FastQC doesn't respects the suffixes of files, but imposes the fastq
# convention of having the read number as '_1' and '_2' before the finishing
# '.fastq[.gz]'. To work with my naming, which is needed for other purposes, I
# have to have two almost identical targets, one for each read mate.

# Make fastqc html reports for all .r[12].fastq.gz files
all_fastqc: $(subst .r1.fastq.gz,.r1_fastqc.html,$(wildcard *.r1.fastq.gz)) $(subst .r2.fastq.gz,.r2_fastqc.html,$(wildcard *.r2.fastq.gz))
	if [ `which multiqc 2>/dev/null` ]; then multiqc -f .; fi

%.r1_fastqc.html: %.r1.fastq.gz
	fastqc $<

%.r2_fastqc.html: %.r2.fastq.gz
	fastqc $<

