# makefile.metawrap
#
# Library makefile to make running metaWRAP programs simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@lnu.se

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
MW_RAW_READS_DIR = SET TO DIRECTORY WITH UNPACKED FASTQ FILES (ENDING WITH _1.fastq and _2.fastq)

MW_THREADS = -t 20
MW_MEMORY = -m 120
MW_QC_OPTS = --skip-bmtagger
MW_BINNING_OPTS = --run-checkm 
MW_BINNING_PROGRAMS = --metabat2 --maxbin2 --concoct 

# This macro is used to specificy which bins to refine using the -A, -B and -C flags,
# e.g. -A all_reads.megahit.binning/concoct_bins -B all_reads.megahit.binning/maxbin2_bins -C all_reads.megahit.binning/metabat2_bins
MW_BIN_REFINE_OPTS =
MW_REASSEMBLE_OPTS = -c 70 -x 10

# *** Internal ***

# MAKECALL_METAWRAP is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_METAWRAP_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `metaWRAP --version | grep metaWRAP`" > $@.makecall
MAKECALL_METAWRAP_PARAMS      = echo "	Called with parameters: $(METAWRAP_OPTS)" >> $@.makecall
MAKECALL_METAWRAP_INFILES     = echo "	Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_METAWRAP             = $(MAKECALL_METAWRAP_VERSION); $(MAKECALL_METAWRAP_PARAMS); $(MAKECALL_METAWRAP_INFILES)

# *** Targets ***

mwqc.out: $(wildcard $(MW_RAW_READS_DIR)/*.fastq)
	@$(MAKECALL_METAWRAP)
	for fwd in $(MW_RAW_READS_DIR)/*_1.fastq; do \
	  echo "--> $$fwd <--" | tee -a $@; \
	  metaWRAP read_qc -o $@.$$(basename $$fwd _1.fastq).d -1 $$fwd -2 $${fwd/_1.fastq/_2.fastq} $(MW_QC_OPTS) $(MW_THREADS) | tee -a $@; \
	done
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.megahit.log: %_1.fastq %_2.fastq
	@$(MAKECALL_METAWRAP)
	metaWRAP assembly -o $(basename $@) -1 $< -2 $(word 2,$^) $(MW_ASSEMBLY_OPTS) $(MW_THREADS) $(MW_MEMORY) > $@ 2>&1
	ln -s $(basename $@)/final_assembly.fasta $(basename $@).fna
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.binning.log: %.fna $(wildcard *_[12].fastq)
	@$(MAKECALL_METAWRAP)
	metaWRAP binning -o $(basename $@) -a $< $(MW_BINNING_PROGRAMS) $(MW_BINNING_OPTS) $(MW_THREADS) $(MW_MEMORY) $(wordlist 2,1000,$^) > $@ 2>&1
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.refinement.log: 
	@$(MAKECALL_METAWRAP)
	metaWRAP bin_refinement -o $(basename $@) $(MW_BIN_REFINE_OPTS) $(MW_THREADS) $(MW_MEMORY) > $@ 2>&1
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.blobology.log: %.fna %.bin_refine/metaWRAP_bins $(wildcard *_[12].fastq)
	@$(MAKECALL_METAWRAP)
	metaWRAP blobology -o $(basename $@) -a $< --bins $(word 2,$^) $(MW_THREADS) $(wordlist 3,1000,$^) > $@
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.quant_bins.log: %.fna %.bin_refine/metaWRAP_bins $(wildcard *_[12].fastq)
	@$(MAKECALL_METAWRAP)
	metaWRAP quant_bins -o $(basename $@) -a $< -b $(word 2,$^) $(MW_THREADS) $(wordlist 3,1000,$^) > $@
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.reassemble_bins.log: %.bin_refine/metaWRAP_bins all_reads_1.fastq all_reads_2.fastq
	@$(MAKECALL_METAWRAP)
	metaWRAP reassemble_bins -o $(basename $@) -b $< -1 $(word 2,$^) -2 $(word 3,$^) $(MW_REASSEMBLE_OPTS) $(MW_THREADS) $(MW_MEMORY) > $@
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.annotate_bins.log: $(BIN_DIR)
	@$(MAKECALL_METAWRAP)
	metaWRAP annotate_bins -o $(basename $@) -b $(BIN_DIR) $(MW_ANNOTATE_OPTS) $(MW_THREADS)
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
