# makefile.mothur
#
# Library makefile to make running separate Mothur commands simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: erik.rikard.daniel@gmail.com

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
# These will be included in the mothur function call, and hence needs to start
# with a comma and include the parameter name, an equal sign and the value,
# e.g.:
# MOTHUR_OPTS = , iters=1000
MOTHUR_OPTS =

# Override the numbers of processors if you have more than one.
NUM_PROCESSORS = 1

# Parameters for classify.seqs with SILVA. Override if you have names
# different from the default values.
SILVA_TEMPLATE_FILE = silva.mothur.nr.alnfna
SILVA_TAXONOMY_FILE = silva.mothur.nr.taxonomy

# *** Internal ***

# MAKECALLMOTHUR is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `mothur --version|grep 'Mothur version'`" > $@.makecall
MAKECALL_PARAMS      = echo "	Called with parameters: $(MOTHUR_OPTS)" >> $@.makecall
MAKECALL_INFILES     = echo "	Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_MOTHUR      = $(MAKECALL_VERSION); $(MAKECALL_PARAMS); $(MAKECALL_INFILES)

# *** Targets ***

all.nr.wang.taxonomies: $(subst .fna,.nr.wang.taxonomy.tsv.gz,$(wildcard *.fna))

%.nr.wang.taxonomy.tsv.gz: %.fna
	@$(MAKECALL_MOTHUR)
	mothur "#classify.seqs(fasta=$<, template=$(SILVA_TEMPLATE_FILE), taxonomy=$(SILVA_TAXONOMY_FILE), processors=$(NUM_PROCESSORS), method=wang$(MOTHUR_OPTS))" | tee $@.out 2>&1
	mv $(basename $(basename $@)) $(basename $@); gzip -f $(basename $@)
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

# Fetch database files
MOTHUR_SILVA_PATH = 

Silva.v132.tgz: Silva.nr_v132.tgz Silva.seed_v132.tgz

Silva.nr_v132.tgz:
	wget https://mothur.org/w/images/3/32/$@

Silva.seed_v132.tgz:
	wget https://mothur.org/w/images/7/71/Silva.seed_v132.tgz
