# makefile.phylo
#
# Library makefile to make running various smaller/simpler phylogenetics
# programs simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@dbb.su.se

SHELL := /bin/bash

# *** Parameters ***

# *** Internal ***

# *** Targets ***

# To handle, and record, deletion of sequences, use this target, with a file,
# %.interesting.faa, containing prioritized sequences and a file containing
# sequences you don't want, deleted_sequences (see next recipe). Make sure
# fasta files have sequences on one line (see %.c.faa target in makefile.misc).
deleted_sequences: $(wildcard problem_sequences.*)
	        sort -u $^ > $@

# Remove deleted sequences from .faa file
REMOVE_RARE = sort -u $(wordlist 2,3,$^) > /tmp/$(basename $@).delete; \
	grep '>' $< | grep -v -F -f /tmp/$(basename $@).delete | sed 's/.*@//' > $@

%.correct_sequences: %.faa %.rare deleted_sequences 
	$(REMOVE_RARE)

%.rare:
	touch $@

%.correct.faa: %.correct_sequences %.faa %.interesting.faa
	cat $(word 3,$^) > $@
	grep -F -A 1 -f $(wordlist 1,2,$^) | grep -v '^--' >> $@

%.interesting.faa:
	touch $@

# Remove deleted_sequences from .fna file 
%.correct_sequences: %.fna deleted_sequences 
	grep '>' $< | grep -v -f $(word 2,$^) | sed 's/.*@//' > $@

%.correct.fna: %.correct_sequences %.fna %.interesting.fna
	cat $(word 3,$^) > $@
	grep -F -A 1 -f $(wordlist 1,2,$^) | grep -v '^--' >> $@

%.interesting.fna:
	touch $@
