# makefile.fastx
#
# Library makefile to make running the programs from the FastX collection
# simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: erik.rikard.daniel@gmail.com

SHELL := /bin/bash

# *** Parameters ***

# *** Internal ***

# MAKECALL_FASTX is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `fastx_collapser -h | grep 'Part of'`" > $@.makecall
MAKECALL_INFILES     = echo "	Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_FASTX      = $(MAKECALL_VERSION); $(MAKECALL_INFILES)

# *** Targets ***

# Run the fastx_collapser on all fastq.gz files.
#
# It converts files from fastq to fasta (.fna.gz) and gives them new names.
# Probably useful before assembly to reduced the amount of data.
fastq2collapse: $(subst .r1.fastq.gz,.collapse.r1.fna.gz,$(wildcard *.r1.fastq.gz)) $(subst .r2.fastq.gz,.collapse.r2.fna.gz,$(wildcard *.r2.fastq.gz))

# The macro that does the job
FASTX_COLLAPSE = gunzip -c $< | fastx_collapser | gzip -c > $@

%.collapse.r1.fna.gz: %.r1.fastq.gz
	$(MAKECALL_FASTX)
	$(FASTX_COLLAPSE)
	echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.collapse.r2.fna.gz: %.r2.fastq.gz
	$(MAKECALL_FASTX)
	$(FASTX_COLLAPS)
	echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
