# makefile.clustalo
#
# Library makefile to make running Clustal Omega simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: erik.rikard.daniel@gmail.com

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
CLUSTALO_OPTS =

# *** Internal ***

# MAKECALLCLUSTALO is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `clustalo --version`" > $@.makecall
MAKECALL_PARAMS      = echo "	Called with parameters: $(CLUSTALO_OPTS)" >> $@.makecall
MAKECALL_INFILES     = echo "	Input files: $^ (`ls -l $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_CLUSTALO      = $(MAKECALL_VERSION); $(MAKECALL_PARAMS); $(MAKECALL_INFILES)

# *** Targets ***

# Align all faa files
clustalo_align_all_faas: $(subst .faa,.co.alnfaa,$(wildcard *.faa))

# Align non-aligned amino acid sequences
%.co.alnfaa: %.faa
	@$(MAKECALL_CLUSTALO)
	clustalo -i $< -o $@ --force $(CLUSTALO_OPTS)
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.co.alnfaa: %.faa.gz
	@$(MAKECALL_CLUSTALO)
	gunzip -c $<  | clustalo -i - -o $@ --force $(CLUSTALO_OPTS)
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

# Align amino acids to an alignment with an hmm profile present (Emits warning about only using
# one of the profiles...)
%.co.hmm.alnfaa: %.faa profile.hmm profile.alnfaa
	@$(MAKECALL_CLUSTALO)
	clustalo -i $< -o $@ --hmm-in=$(word 2,$^) --profile1=$(word 3,$^) --force $(CLUSTALO_OPTS)
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

# Align non-aligned nucleotide sequences
%.co.alnfna: %.fna
	@$(MAKECALL_CLUSTALO)
	clustalo -i $< -o $@ --force $(CLUSTALO_OPTS)
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.co.alnfna: %.fna.gz
	@$(MAKECALL_CLUSTALO)
	gunzip -c $<  | clustalo -i - -o $@ --force $(CLUSTALO_OPTS)
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
