###
# Library makefile for directories you run Diamond from.
#
# Contains "recipies", i.e. targets, both for creating Diamond databases and
# running Diamond.
#
# Author: daniel.lundin@lnu.se
###

%.dmnd: %.faa
	diamond makedb --in $< -d $(basename $@)
