# makefile.dada2
#
# Library makefile to make running DADA2 simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: __AUTHOR_EMAIL__

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
DADA2_FILTER_OPTS    = --verbose --trimleft=8,8 --trunclen=280,200
DADA2_ERRMODELS_OPTS = --verbose --nsamples=24 --maxconsist=30 
DADA2_CLEAN_OPTS     = --verbose
DADA2_BIMERAS_OPTS   = --verbose --minab=8 --overab=4 --oneoff 

# *** Internal ***

# MAKECALLDADA2 is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_FILTER_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `dada2filter --version`" > $@.makecall 2>&1
MAKECALL_ERRMODELS_VERSION  = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `dada2errmodels --version`" > $@.makecall 2>&1
MAKECALL_CLEAN_VERSION      = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `dada2cleanNmerge --version`" > $@.makecall 2>&1
MAKECALL_BIMERAS_VERSION    = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `dada2bimeras --version`" > $@.makecall 2>&1
MAKECALL_FILTER_PARAMS      = echo "	Called with parameters: $(DADA2_FILTER_OPTS)" >> $@.makecall
MAKECALL_ERRMODELS_PARAMS   = echo "	Called with parameters: $(DADA2_ERRMODELS_OPTS)" >> $@.makecall
MAKECALL_CLEAN_PARAMS       = echo "	Called with parameters: $(DADA2_CLEAN_OPTS)" >> $@.makecall
MAKECALL_BIMERAS_PARAMS     = echo "	Called with parameters: $(DADA2_BIMERAS_OPTS)" >> $@.makecall
MAKECALL_INFILES            = echo "	Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_DADA2FILTER        = $(MAKECALL_FILTER_VERSION); $(MAKECALL_FILTER_PARAMS); $(MAKECALL_INFILES)
MAKECALL_DADA2ERRMODELS     = $(MAKECALL_ERRMODELS_VERSION); $(MAKECALL_ERRMODELS_PARAMS); $(MAKECALL_INFILES)
MAKECALL_DADA2CLEAN         = $(MAKECALL_CLEAN_VERSION); $(MAKECALL_CLEAN_PARAMS); $(MAKECALL_INFILES)
MAKECALL_DADA2BIMERAS       = $(MAKECALL_BIMERAS_VERSION); $(MAKECALL_BIMERAS_PARAMS); $(MAKECALL_INFILES)

# *** Targets ***

# 1. Truncate and filter (QC)
dada2filter.out: $(wildcard *.fastq.gz)
	@$(MAKECALL_DADA2FILTER)
	dada2filter $(DADA2_FILTER_OPTS) >$@ 2>&1
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

# 2. Estimate error models
dada2errmodels.out: dada2filter.out
	@$(MAKECALL_DADA2ERRMODELS)
	dada2errmodels $(DADA2_ERRMODELS_OPTS) >$@ 2>&1
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall


# 3. Correct and merge reads
dada2.cleaned.merged.rds: seq.dada2errmodels.fwd.errorates.rds seq.dada2errmodels.rev.errorates.rds 
	@$(MAKECALL_DADA2CLEAN)
	dada2cleanNmerge $(DADA2_CLEAN_OPTS) --fwderrmodel=$< --reverrmodel=$(word 2,$^) >$(basename $@).out 2>&1
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall


# 4. Filter out bimeras
dada2.cleaned.merged.bimeras.rds: dada2.cleaned.merged.rds
	@$(MAKECALL_DADA2BIMERAS)
	dada2bimeras --verbose --seqtabfile=$< --prefix=$(basename $@) $(DADA2_BIMERAS_OPTS) >$(basename $@).out 2>&1
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall


# The following two are for technical reasons
seq.dada2errmodels.fwd.errorates.rds: dada2errmodels.out

seq.dada2errmodels.rev.errorates.rds: dada2errmodels.out
