# makefile.blast
#
# Library makefile to make running NCBI's BLAST+ programs simpler.
#
# Include the full path of this file in your Makefile 
#
# Author: daniel.lundin@lnu.se

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
# This needs to point to wherever you store NCBI data for the refseq targets to
# work. Make sure it's a relative path, probably to a symlink within the local
# copy of the project. (Don't want to set environment variables.)
NCBI_BLAST_DB_PATH = YOU NEED TO SET THE NCBI_BLAST_DB_PATH VARIABLE (see makefile.blast)
BLAST_PROTEIN_DB = YOU NEED TO SET THE BLAST_PROTEIN_DB VARIABLE (see makefile.blast)

# *** Internal ***

# MAKECALL_BLAST_BLAST is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_BLAST_VERSION     = echo "$$(date +"%Y%m%d %H:%M:%S"): $@ was made with $$(blastp --version|grep 'blastp:')" > $@.makecall
MAKECALL_BLAST_NCBI_DBS    = echo "	Called with path to NCBI dbs: $(NCBI_BLAST_DB_PATH)" >> $@.makecall
MAKECALL_BLAST_INFILES     = echo "	Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_BLAST             = $(MAKECALL_BLAST_VERSION); $(MAKECALL_BLAST_NCBI_DBS); $(MAKECALL_BLAST_INFILES)

# *** Targets ***

%.refseq_protein.blasttab.gz: %.fna
	$(MAKECALL_BLAST)
	blastx -db $(NCBI_BLAST_DB_PATH)/refseq_protein -query $< -outfmt 6 | gzip -c > $@
	echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.blastp6.tsv.gz: %.faa
	blastp -db $(BLAST_PROTEIN_DB) -query $< -outfmt 6 | gzip -c > $@

%.blastdb: %.faa
	makeblastdb -in $< -out $(basename $@) -dbtype prot
	touch $@

%.blastdb: %.faa.gz
	gunzip -c $< | makeblastdb -out $(basename $(basename $@)) -title $(basename $@) -dbtype prot
	touch $@
