# makefile.uniprot
#
# Library makefile to make downloading data from Uniprot simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@dbb.su.se

SHELL := /bin/bash

FETCH = wget https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/$@

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#

# *** Internal ***

# *** Targets ***
uniprot.faa.gz: uniprot_sprot.fasta.gz uniprot_trembl.fasta.gz
	cat $^ > $@

uniprot_sprot.fasta.gz:
	$(FETCH)

uniprot_trembl.fasta.gz:
	$(FETCH)

uniprot_sprot.dat.gz:
	$(FETCH)

uniprot_trembl.dat.gz:
	$(FETCH)

uniprot_sprot.xml.gz:
	$(FETCH)

uniprot_trembl.xml.gz:
	$(FETCH)

uniref90.fasta.gz:
	wget https://ftp.uniprot.org/pub/databases/uniprot/current_release/uniref/uniref90/uniref90.fasta.gz

uniref90.xml.gz:
	wget https://ftp.uniprot.org/pub/databases/uniprot/current_release/uniref/uniref90/uniref90.xml.gz

uniref50.fasta.gz:
	wget https://ftp.uniprot.org/pub/databases/uniprot/current_release/uniref/uniref50/uniref50.fasta.gz

uniref50.xml.gz:
	wget https://ftp.uniprot.org/pub/databases/uniprot/current_release/uniref/uniref50/uniref50.xml.gz
