# makefile.megahit
#
# Library makefile to make running MEGAHIT simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: erik.rikard.daniel@gmail.com

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.

# To use 20 cores, set to -t 20
MEGAHIT_OPTS = 

# *** Internal ***

# MAKECALLMEGAHIT is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_MEGAHIT_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `megahit --version`" > $@.makecall
MAKECALL_MEGAHIT_PARAMS      = echo "	Called with parameters: $(MEGAHIT_OPTS)" >> $@.makecall
MAKECALL_MEGAHIT_INFILES     = echo "	Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_MEGAHIT_MEGAHIT     = $(MAKECALL_MEGAHIT_VERSION); $(MAKECALL_MEGAHIT_PARAMS); $(MAKECALL_MEGAHIT_INFILES)

comma:= ,
empty:=
space:= $(empty) $(empty)

# *** Targets ***

all.megahit_out: $(wildcard *.r?.fastq.gz)
	$(MAKECALL_MEGAHIT_MEGAHIT)
	megahit \
	  -1 $(subst $(space),$(comma),$(sort $(filter %.r1.fastq.gz,$^))) \
	  -2 $(subst $(space),$(comma),$(sort $(filter %.r2.fastq.gz,$^))) \
	  -o $@ $(MEGAHIT_OPTS) 2>&1 | tee $@.out
	echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

all_separate_megahits: $(subst .r1.fastq.gz,.megahit_out,$(wildcard *.r1.fastq.gz))

%.megahit_out: %.r1.fastq.gz %.r2.fastq.gz
	$(MAKECALL_MEGAHIT_MEGAHIT)
	megahit -1 $< -2 $(word 2,$^) -o $@ $(MEGAHIT_OPTS) 2>&1 | tee $@.out
	echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

# Creates tar balls and gzipped fasta files for all megahit assemblies run in
# this directory.
all_megahit_out.tar.gz: $(subst .megahit_out,.megahit_out.tar.gz,$(wildcard *.megahit_out))

# This creates a gzipped tar ball of the content of the %.megahit_out directory
# that contains all the output from megahit. It also creates a gzipped copy of
# the final.contigs.fa file that is the most important output from megahit.
# After you have run this target you can delete the %.megahit_out directory and
# save a lot of space.
%.megahit_out.tar.gz: %.megahit_out
	gzip -c $</final.contigs.fa > $(basename $<).megahit.fna.gz
	tar cfz $@ $<
