# makefile.silva
#
# Library makefile to make downloading and handling files from the Silva
# database simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: erik.rikard.daniel@gmail.com

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
# The current release of Silva, e.g. "132" (without quotation marks).
SILVA_RELEASE =

# *** Internal ***

# *** Targets ***

# When you rerun any of the targets below, you need to delete the dependencies
# (just symlinks) first.

# Download the Ref databases, LSU and SSU.
ref_dbs: SILVA_CURRENT_LSURef_tax_silva.fna.gz SILVA_CURRENT_SSURef_tax_silva.fna.gz

SILVA_CURRENT_LSURef_tax_silva.fna.gz:
	wget -c https://www.arb-silva.de/fileadmin/silva_databases/release_$(SILVA_RELEASE)/Exports/SILVA_$(SILVA_RELEASE)_LSURef_tax_silva.fasta.gz 
	ln -s SILVA_$(SILVA_RELEASE)_LSURef_tax_silva.fasta.gz $@

SILVA_CURRENT_SSURef_tax_silva.fna.gz:
	wget -c https://www.arb-silva.de/fileadmin/silva_databases/release_$(SILVA_RELEASE)/Exports/SILVA_$(SILVA_RELEASE)_SSURef_tax_silva.fasta.gz 
	ln -s SILVA_$(SILVA_RELEASE)_SSURef_tax_silva.fasta.gz $@

SILVA_CURRENT_LSURef_tax_silva.taxonomy.txt.gz:
	wget -c https://www.arb-silva.de/fileadmin/silva_databases/current/Exports/taxonomy/taxmap_embl_lsu_ref_$(SILVA_RELEASE).txt.gz
	ln -s taxmap_embl_lsu_ref_$(SILVA_RELEASE).txt.gz $@

SILVA_CURRENT_SSURef_tax_silva.taxonomy.txt.gz:
	wget -c https://www.arb-silva.de/fileadmin/silva_databases/current/Exports/taxonomy/taxmap_embl_ssu_ref_$(SILVA_RELEASE).txt.gz
	ln -s taxmap_embl_ssu_ref_$(SILVA_RELEASE).txt.gz $@

# Download the large Parc databases, LSU and SSU.
parc_dbs: SILVA_CURRENT_LSUParc_tax_silva.fna.gz SILVA_CURRENT_SSUParc_tax_silva.fna.gz

SILVA_CURRENT_LSUParc_tax_silva.fna.gz:
	wget -c https://www.arb-silva.de/fileadmin/silva_databases/release_$(SILVA_RELEASE)/Exports/SILVA_$(SILVA_RELEASE)_LSUParc_tax_silva.fasta.gz 
	ln -s SILVA_$(SILVA_RELEASE)_LSUParc_tax_silva.fasta.gz $@

SILVA_CURRENT_SSUParc_tax_silva.fna.gz:
	wget -c https://www.arb-silva.de/fileadmin/silva_databases/release_$(SILVA_RELEASE)/Exports/SILVA_$(SILVA_RELEASE)_SSUParc_tax_silva.fasta.gz 
	ln -s SILVA_$(SILVA_RELEASE)_SSUParc_tax_silva.fasta.gz $@

# This creates unzipped versions of all SILVA_CURRENT_*fna.gz symlinks
gunzip_current_fnas: $(subst .fna.gz,.fna,$(wildcard SILVA_CURRENT*.fna.gz))

# Concatenate current SSU and LSU; good for filtering programs for instance.
SILVA_CURRENT_Parc_tax_silva.fna: SILVA_CURRENT_LSUParc_tax_silva.fna SILVA_CURRENT_SSUParc_tax_silva.fna
	cat $^ > $@

SILVA_CURRENT_Ref_tax_silva.fna: SILVA_CURRENT_LSURef_tax_silva.fna SILVA_CURRENT_SSURef_tax_silva.fna
	cat $^ > $@

# Fetch QIIME2 database at 99% for sklearn algorithm
silva-99-nb-classifier.qza:
	rm -f $@
	wget -c https://data.qiime2.org/$(QIIME_RELEASE)/common/silva-$(SILVA_RELEASE)-99-nb-classifier.qza
	ln -s silva-$(SILVA_RELEASE)-99-nb-classifier.qza $@

%.fna: %.fna.gz
	gunzip -c $< > $@

%.u2t.fna: %.fna
	sed '/^>/!s/U/T/g' $< > $@
