# makefile.epa-ng
#
# Library makefile to make running epa-ng simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: michelle.hagen98@web.de

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
EPA_NG_OPTS =

# *** Internal ***

# MAKECALL_EPA_NG is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_EPA_NG_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `epa-ng --version | grep EPA-ng`" > $@.makecall
MAKECALL_EPA_NG_PARAMS      = echo "    Called with parameters: $(__PGM___OPTS)" >> $@.makecall
MAKECALL_EPA_NG_INFILES     = echo "    Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_EPA_NG             = $(MAKECALL_EPA_NG_VERSION); $(MAKECALL_EPA_NG_PARAMS); $(MAKECALL_EPA_NG_INFILES)

# *** Targets ***

# Target to rename the Reference Alignment, if it has been reduced by RAxML to match the epa_result target
%.raxml.alnfaa: %.raxml.reduced.alnfaa
        mv $(basename $(basename $@)).raxml.reduced.alnfaa $@

# Here epa-ng takes as input: 
# - ReferenceTree (rooted and safed as newick file)
# - ReferenceAlignment (with the same id as the RAxML RT, raxml .phy file has been converted back to .alnfaa)
# - QueryAlignment (created with hmmer)
# 
# epa-ng creates pre-named output files in the current directory:
# - epa_info.log
# - epa_results.jplace
# so RT, RA and QS have to be in the same directory with no other RT, RA or QS files!

epa_result.jplace: $(wildcard *.rooted.newick) $(wildcard *.raxml.alnfaa) $(wildcard *.hmmer.alnfaa)
        @$(MAKECALL_EPA_NG)
        epa-ng --tree $< --ref-msa $(word 2,$^) --query $(word 3,$^) --outdir . --model LG+G4+F
        @echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
