# makefile.img
#
# Library makefile containing instructions for simple image manipulations
# (currently just converting pdf files to png).
#
# Include the full path of this file in your Makefile ...
#
# Author: erik.rikard.daniel@gmail.com

THIS IS REPLACED WITH makefile.figures
