# makefile.last
#
# Library makefile to make running the LAST aligner simpler.
#
# Include the full path of this file in your Makefile and making databases and
# running the aligner (lastal) can be done via make. See documentation in in
# the biomakefile Git repository: doc/makefile.md and documentation for
# individual targets below.
#
# Author: daniel.lundin@lnu.se

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
# LAST_DB_PATH sets the directory where to look for the database files. The default
# is the current directory.
LAST_DB_PATH = .

# LASTAL_OPTS sets parameters for the lastal run. (-P4 tells it to use 4 cpu
# threads, -e200 to only keep hits with at least 200 score.)
LASTAL_OPTS = -P4 -e200

# *** Targets ***

# Run lastal against the NCBI RefSeq RNA database for all fastq.gz files
# present in the current directory.
all_refseq_rna.maf.gzs: $(subst .fastq.gz,.refseq_rna.maf.gz,$(wildcard *.fastq.gz))

# Converts all .maf.gz files (output files from lastal) to tables that are
# sufficiently similar to BLAST's -m 8 tabular format to allow import into
# MEGAN.
all_lasttabs: $(subst .maf.gz,.lasttab.gz,$(wildcard *.maf.gz))

%.refseq_rna.maf.gz: %.fastq.gz
	gunzip -c RNA_3-0.2_2012-05-16.lane1.r1.fastq.gz | lastal $(LASTAL_OPTS) -Q1 $(LAST_DB_PATH)/refseq_rna.lastdb | gzip -c > RNA_3-0.2_2012-05-16.lane1.r1.refseq_rna.maf.gz

%.lasttab.gz: %.maf.gz
	gunzip -c $< | maf-convert tab | awk '/^[^#]/ { print $$7 "\t" $$2 "\t100\t" $$4 "\t0\t0\t" $$8 "\t" $$11 "\t" $$3 "\t" $$6 "\t1e-100\t" $$1 }' | sort -k 1,1 -k 12,12rn | gzip -c > $@
