# makefile.epa-ng
#
# Library makefile to make running epa-ng simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: michelle.hagen98@web.de

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
EPA_NG_OPTS =

# *** Internal ***

# MAKECALL_EPA_NG is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_EPA_NG_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `epa-ng --version | grep EPA-ng`" > $@.makecall
MAKECALL_EPA_NG_PARAMS      = echo "    Called with parameters: $(EPA_NG_OPTS)" >> $@.makecall
MAKECALL_EPA_NG_INFILES     = echo "    Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_EPA_NG             = $(MAKECALL_EPA_NG_VERSION); $(MAKECALL_EPA_NG_PARAMS); $(MAKECALL_EPA_NG_INFILES)

# *** Targets ***

# Here epa-ng takes as input: 
# - ReferenceTree (rooted and safed as newick file) %.rfmask.hmmer.LGG4F.raxml.bestTree.rooted.newick
# - ReferenceAlignment (with the same id as the RAxML RT, raxml .phy file has been converted back to .alnfaa) %.rfmask.hmmer.LGG4F.raxml.alnfaa
# - QueryAlignment (created with hmmer) %.qs.rfmask.hmmer.alnfaa
# 
# epa-ng creates pre-named output files in the current directory:
# - epa_info.log
# - epa_results.jplace

%.epa_result.jplace: %.rfmask.hmmer.LGG4F.raxml.bestTree.rooted.newick %.rfmask.hmmer.LGG4F.raxml.alnfaa %.qs.rfmask.hmmer.alnfaa
	@$(MAKECALL_EPA_NG)
	epa-ng --tree $< --ref-msa $(word 2,$^) --query $(word 3,$^) --outdir . --model LG+G4+F
	mv epa_result.jplace $@
	mv epa_info.log $(basename $(basename $@)).epa_info.log
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
	
