# makefile.imgmer
#
# Library makefile to make handling downloads from IMG/MER easier
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@dbb.su.se daniel.lundin@lnu.se

SHELL := /bin/bash

EXTRACT_AND_LINK = echo -n "--> $@ "; e=$$(echo $@ | sed "s/$$(basename $< .tar.gz)//"); f=$$(tar tfz $< | grep $$e); echo -n "($$f)"; if [ "x$$f" = "x" ]; then touch $@; else tar xzf $< $$f && if [ ! -e $@ ]; then ln -s $(basename $(basename $<))/$@ .; fi; touch $(basename $(basename $<))/*a.faa; fi; echo " <--"

# This URL leads to genome description pages. Requires logging in...
#https://img.jgi.doe.gov/cgi-bin/mer/main.cgi?section=TaxonDetail&page=taxonDetail&taxon_oid=

# *** Targets ***

all_READMEs: $(subst .tar.gz,.README,$(wildcard *.tar.gz))

all_configs: $(subst .tar.gz,.config,$(wildcard *.tar.gz))

all_assembled_faas: $(subst .tar.gz,.a.faa,$(wildcard *.tar.gz)) $(subst .tar.gz,.genes.faa,$(wildcard *.tar.gz))

gzip_faas:
	for f in $$(find . -maxdepth 2 -name "*.faa" -type f -size +0c); do \
	  l=$$(find -L . -samefile $$f -xtype l); \
	  echo "--> $${f} ($$l) <--"; \
	  pigz $$f; rm $$l; ln -s $${f}.gz; \
	done; \

# Extract README (identical for all, so no real need)
%.README: %.tar.gz
	tar xzf $< $$(tar tfz $< | grep README) && if [ -e $@ ]; then ln -s $(basename $(basename $<))/README* $@; fi
	touch $(basename $(basename $<))/README*

# Extract config 
%.config: %.tar.gz
	@$(EXTRACT_AND_LINK)

# Extract assembled faa file
%.a.faa: %.tar.gz
	@$(EXTRACT_AND_LINK)

# Extract assembled faa file, old format with "genes" in name
%.genes.faa: %.tar.gz
	@$(EXTRACT_AND_LINK)
