# makefile.splitstree
#
# Library makefile to make running SplitsTree simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@dbb.su.se

SHELL := /bin/bash

# *** Parameters ***

# (Tries to) clean up an aligned fasta file so SplitsTree (v. 4) will accept
# it. (DH might be working on a new version which is less picky.)
%.st.alnfaa: %.alnfaa
	sed '/^>/s/\[\+//' $< | sed '/^>/s/\]\+//g' | sed '/^>/s/-//g' | sed '/^>/s/[:,]//g' | sed '/^>/s/ \+/_/g' > $@
