# makefile.checkm
#
# Library makefile to make running CheckM simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@lnu.se

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
# For CHECKM_LINEAGE_WF_OPTS use e.g. --threads 8 --pplacer_threads 8
CHECKM_LINEAGE_WF_OPTS =
CHECKM_QA_OPTS =

# *** Internal ***

# MAKECALL_CHECKM is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_CHECKM_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with $(checkm|grep -o 'CheckM v[0-9].\+')" > $@.makecall
MAKECALL_CHECKM_PARAMS      = echo "	Called with parameters: $(CHECKM_LINEAGE_WF_OPTS)" >> $@.makecall
MAKECALL_CHECKM_INFILES     = echo "	Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_CHECKM             = $(MAKECALL_CHECKM_VERSION); $(MAKECALL_CHECKM_PARAMS); $(MAKECALL_CHECKM_INFILES)

CHECKM_OUT_TO_TSV =  tail -n +$$(grep -n 'Bin Id' $<|sed 's/:.*//') $< | grep -v '^-\+' | sed 's/^ \+//' | sed 's/ \+$$//' | sed 's/  \+/\t/g' | grep -v 'INFO:.*Current' > $@

# *** Targets ***

### # This will have to be updated when new data is released...
### fetch_data:
### 	wget https://data.ace.uq.edu.au/public/CheckM_databases/checkm_data_2015_01_16.tar.gz
### 
### # This runs checkm lineage_wf on all bins in .fna files in
### # the current directory; includes gene calling.
### checkm.lineage_wf.fna.out: $(wildcard *.fna)
### 	@$(MAKECALL_CHECKM)
### 	checkm lineage_wf $(CHECKM_LINEAGE_WF_OPTS) . checkm/ 2>&1 | tee $@
### 	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
### 
### # Run checkm lineage_wf on all bins in the genome_bins subdirectory
### checkm.lineage_wf.genome_bins.fna.out: $(wildcard genome_bins/*.fna)
### 	@$(MAKECALL_CHECKM)
### 	checkm lineage_wf $(CHECKM_LINEAGE_WF_OPTS) genome_bins/ $(basename $@).d | tee $@
### 	ln -s $(basename $@).d checkm
### 	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
### 
### # This runs checkm lineage_wf on all bins in .faa files in
### # the current directory.
### checkm.lineage_wf.faa.out: $(wildcard *.faa)
### 	@$(MAKECALL_CHECKM)
### 	checkm lineage_wf $(CHECKM_LINEAGE_WF_OPTS) -x faa --genes --file $@ . checkm/ 2>&1 | tee $(basename $@).err
### 	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
### 
### # This file, or the next, will contain completeness etc.
### checkm.lineage_wf.faa.tsv: checkm.lineage_wf.faa.out
### 	$(CHECKM_OUT_TO_TSV)
### 
### checkm.lineage_wf.fna.tsv: checkm.lineage_wf.fna.out
### 	$(CHECKM_OUT_TO_TSV)
### 
### checkm.lineage_wf.genome_bins.fna.tsv: checkm.lineage_wf.genome_bins.fna.out
### 	$(CHECKM_OUT_TO_TSV)
### 
# Run this instead of the above
checkm.lineage_wf.qa_2.tsv: checkm/lineage.ms
	checkm qa -o 2 --tab_table -f $@ $(CHECKM_QA_OPTS) $< $(dir $<)

checkm/lineage.ms: $(wildcard genome_bins/*.fna)
	checkm lineage_wf $(CHECKM_LINEAGE_WF_OPTS) genome_bins/ $(dir $@)

### checkm.tree_qa.out: $(wildcard checkm.lineage_wf*out)
### 	@$(MAKECALL_CHECKM)
### 	checkm tree_qa --file $@ checkm/ 2>&1 | tee $(basename $@).err
### 	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
### 
### checkm.tree_qa.tsv: checkm.tree_qa.out
### 	$(CHECKM_OUT_TO_TSV)
### 
### checkm.bin_qa_plot.faa.pdf: checkm.lineage_wf.faa.out
### 	checkm bin_qa_plot --image_type pdf -x faa . checkm/ checkm/plots
### 
### checkm.bin_qa_plot.fna.pdf: checkm.lineage_wf.fna.out
### 	checkm bin_qa_plot --image_type pdf . checkm/ checkm/plots
