# makefile.metabat
#
# Library makefile to make running metabat simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@lnu.se

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
METABAT_OPTS = --verbose

# *** Internal ***

# MAKECALL_METABAT is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_METABAT_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with $(metabat --help 2>&1|grep -o 'version [0-9.]*')" > $@.makecall
MAKECALL_METABAT_PARAMS      = echo "	Called with parameters: $(METABAT_OPTS)" >> $@.makecall
MAKECALL_METABAT_INFILES     = echo "	Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_METABAT             = $(MAKECALL_METABAT_VERSION); $(MAKECALL_METABAT_PARAMS); $(MAKECALL_METABAT_INFILES)

# *** Targets ***

%.metabat: %.fna $(wildcard *.bam)
	@$(MAKECALL_METABAT)
	runMetaBat.sh $(METABAT_OPTIONS) $^ 2>&1 | tee $@.out
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
