# makefile.mb
#
# Library makefile to make running the MrBayes simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@dbb.su.se

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
MRBAYES_OPTS =

# *** Internal ***

# MAKECALL_MRBAYES is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_MRBAYES_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `echo 'Version; quit;' | mb | grep -o 'MrBayes v[0-9a-f.]\+' | sort -u`" > $@.makecall
MAKECALL_MRBAYES_PARAMS      = echo "	Called with parameters: $(MRBAYES_OPTS)" >> $@.makecall
MAKECALL_MRBAYES_INFILES     = echo "	Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_MRBAYES             = $(MAKECALL_MRBAYES_VERSION); $(MAKECALL_MRBAYES_PARAMS); $(MAKECALL_MRBAYES_INFILES)

# *** Targets ***

# Make an alnfaa file with MrBayes formatted names, ready to turn into Nexus with Seaview.
# In addition to this, you have to make sure names are no longer than 99 characters.
%.mb.alnfaa: %.alnfaa
	sed 's/@/_accno_/' | sed "s/'//g" | sed 's:["/]::g' $< > $@

%.mb.out: %.mb
	mb $< | tee $@

###%.suffix0: %.suffix1 %.suffix1 %.suffixn
###	@$(MAKECALL_MRBAYES)
###	__PGM_CALL__
###	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
