# makefile.last
#
# Library makefile to make running the LAST aligner simpler.
#
# Include the full path of this file in your Makefile and making databases and
# running the aligner (lastal) can be done via make. See documentation in in
# the biomakefile Git repository: doc/makefile.md and documentation for
# individual targets below.
#
# Author: daniel.lundin@lnu.se

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
# LAST_DB_PATH sets the directory where to look for the database files. The default
# is the current directory.
LAST_DB_PATH = .

# LASTAL_OPTS sets parameters for the lastal run. (-P4 tells it to use 4 cpu
# threads, -e200 to only keep hits with at least 200 score.)
LASTAL_OPTS = -P4 -e200

# If you use something else than the sanger flavour of fastq you should reset
# this one, see the LAST documentation: http://last.cbrc.jp/. Not needed for 
# modern, at the time of writing, Illumina data.
FASTQ_FORMAT = -Q1

# *** Macros ***
AWK_LASTTAB2MEGANTAB = awk '/^[^\#]/ { print $$7 "\t" $$2 "\t100\t" $$4 "\t0\t0\t" $$8 "\t" $$11 "\t" $$3 "\t" $$6 "\t1e-100\t" $$1 }' | sort -k 1,1 -k 12,12rn 

# *** Targets ***

# Run lastal against the NCBI RefSeq RNA database for all fastq.gz files
# present in the current directory.
all_refseq_rna.fastq2maf.gzs: $(subst .fastq.gz,.refseq_rna.maf.gz,$(wildcard *.fastq.gz))

all_refseq_rna.fastq2mafs: $(subst .fastq.gz,.refseq_rna.maf,$(wildcard *.fastq.gz))

all_refseq_rna.fna2mafs: $(subst .fna,.refseq_rna.maf,$(wildcard *.fna)) $(subst .fna.gz,.refseq_rna.maf,$(wildcard *.fna.gz))

# Converts all .maf.gz files (output files from lastal) to tables that are
# sufficiently similar to BLAST's -m 8 tabular format to allow import into
# MEGAN.
all_megantabs: $(subst .maf.gz,.megantab.gz,$(wildcard *.maf.gz)) $(subst .maf,.megantab.gz,$(wildcard *.maf))

%.refseq_rna.maf: %.fastq.gz
	gunzip -c $< | lastal $(LASTAL_OPTS) $(FASTQ_FORMAT) $(LAST_DB_PATH)/refseq_rna.lastdb > $@

%.refseq_rna.maf: %.fna
	lastal $(LASTAL_OPTS) $(LAST_DB_PATH)/refseq_rna.lastdb $< > $@

%.refseq_rna.maf: %.fna.gz
	gunzip -c $< | lastal $(LASTAL_OPTS) $(LAST_DB_PATH)/refseq_rna.lastdb > $@

%.refseq_rna.maf.gz: %.fastq.gz
	gunzip -c $< | lastal $(LASTAL_OPTS) $(FASTQ_FORMAT) $(LAST_DB_PATH)/refseq_rna.lastdb | gzip -c > $@

%.megantab.gz: %.maf
	maf-convert tab $< | $(AWK_LASTTAB2MEGANTAB) | gzip -c > $@

%.megantab.gz: %.maf.gz
	gunzip -c $< | maf-convert tab | $(AWK_LASTTAB2MEGANTAB) | gzip -c > $@

# Creating the LAST database.

# Protein sequences in a file ending with .faa
#
# At least 24 GiB memory for Refseq?
%.lastdb: %.faa
	lastdb -p -c $@ $<
	touch $@

# Nucleotide sequences in a file ending with .fna
%.lastdb: %.fna
	lastdb -c $@ $<
	touch $@
