# makefile.last
#
# Library makefile to make running the LAST aligner simpler.
#
# Include the full path of this file in your Makefile and making databases and
# running the aligner (lastal) can be done via make. See documentation in in
# the biomakefile Git repository: doc/makefile.md and documentation for
# individual targets below.
#
# Author: daniel.lundin@lnu.se

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
# LAST_DB_PATH sets the directory where to look for the database files. The default
# is the current directory.
LAST_DB_PATH = .

# LASTAL_OPTS sets parameters for the lastal run. (-P4 tells it to use 4 cpu
# threads, -e200 to only keep hits with at least 200 score.)
LASTAL_OPTS = -P4 -e200

# If you use something else than the sanger flavour of fastq you should reset
# this one, see the LAST documentation: http://last.cbrc.jp/. Not needed for 
# modern, at the time of writing, Illumina data.
FASTQ_FORMAT = -Q1

# *** Internal ***
#
# *Don't redefine!*

# AWK_LASTTAB2MEGANTAB Defines an awk call that reformats LAST's tabular output
# so that it can be used with MEGAN.
AWK_LASTTAB2MEGANTAB = awk '/^[^\#]/ { print $$7 "\t" $$2 "\t100\t" $$4 "\t0\t0\t" $$8 "\t" $$11 "\t" $$3 "\t" $$6 "\t1e-100\t" $$1 }' | sort -k 1,1 -k 12,12rn 

# MAKECALL_LAST is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
MAKECALL_VERSION      = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `lastal --version`" > $@.makecall
MAKECALL_MT_VERSION   = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with transformation: $(AWK_LASTTAB2MEGANTAB)" > $@.makecall
MAKECALL_PARAMS       = echo "	Called with parameters: $(LASTAL_OPTS)" >> $@.makecall
MAKECALL_DB_RFRNA     = echo "	Database: $(DIAMOND_DB_PATH)/refseq_rna (`ls -l $(LAST_DB_PATH)/refseq_rna.lastdb`)" >> $@.makecall
MAKECALL_INFILES      = echo "	Input files: $^ (`ls -l $^`)" >> $@.makecall
MAKECALL_LASTAL_RFRNA = $(MAKECALL_VERSION); $(MAKECALL_PARAMS); $(MAKECALL_DB_RFRNA); $(MAKECALL_INFILES)
MAKECALL_MEGANTAB     = $(MAKECALL_MT_VERSION); $(MAKECALL_INFILES)
MAKECALL_MAKEDB       = $(MAKECALL_VERSION); $(MAKECALL_INFILES)

# *** Targets ***

# Run lastal against the NCBI RefSeq RNA database for all fastq.gz files
# present in the current directory.
all_refseq_rna.fastq2mafs: $(subst .fastq.gz,.refseq_rna.maf.gz,$(wildcard *.fastq.gz))

all_refseq_rna.fna2mafs: $(subst .fna,.refseq_rna.maf.gz,$(wildcard *.fna)) $(subst .fna.gz,.refseq_rna.maf.gz,$(wildcard *.fna.gz))

# Converts all .maf.gz files (output files from lastal) to tables that are
# sufficiently similar to BLAST's -m 8 tabular format to allow import into
# MEGAN.
all_megantabs: $(subst .maf.gz,.megantab.gz,$(wildcard *.maf.gz)) $(subst .maf,.megantab.gz,$(wildcard *.maf))

# Here comes individual pattern rules. Defines how programs are actually called
%.refseq_rna.maf.gz: %.fna.gz
	$(MAKECALL_LASTAL_RFRNA)
	gunzip -c $< | lastal $(LASTAL_OPTS) $(LAST_DB_PATH)/refseq_rna.lastdb | gzip -c > $@
	echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.refseq_rna.maf.gz: %.fastq.gz
	$(MAKECALL_LASTAL_RFRNA)
	gunzip -c $< | lastal $(LASTAL_OPTS) $(FASTQ_FORMAT) $(LAST_DB_PATH)/refseq_rna.lastdb | gzip -c > $@
	echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.megantab.gz: %.maf
	$(MAKECALL_MEGANTAB)
	maf-convert tab $< | $(AWK_LASTTAB2MEGANTAB) | gzip -c > $@
	echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.megantab.gz: %.maf.gz
	$(MAKECALL_MEGANTAB)
	gunzip -c $< | maf-convert tab | $(AWK_LASTTAB2MEGANTAB) | gzip -c > $@
	echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

# Creating the LAST database.

# Protein sequences in a file ending with .faa
#
# At least 24 GiB memory for RefSeq protein
%.lastdb: %.faa
	$(MAKECALL_MAKEDB)
	lastdb -p -c $@ $<
	echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
	touch $@

# Nucleotide sequences in a file ending with .fna
%.lastdb: %.fna
	$(MAKECALL_MAKEDB)
	lastdb -c $@ $<
	echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
	touch $@
