# makefile.pear
#
# Library makefile to make running the PEAR program simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: erik.rikard.daniel@gmail.com

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
PEAR_OPTS = -j 6

# *** Internal ***

# MAKECALLPEAR is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `pear --version`" > $@.makecall
MAKECALL_PARAMS      = echo "	Called with parameters: $(PEAR_OPTS)" >> $@.makecall
MAKECALL_INFILES     = echo "	Input files: $^ (`ls -l $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_PEAR      = $(MAKECALL_VERSION); $(MAKECALL_PARAMS); $(MAKECALL_INFILES)

# *** Targets ***

fastq.gzs2pears: $(subst .r1.fastq.gz,.pear.out,$(wildcard *.r1.fastq.gz))

%.pear.out: %.r1.fastq.gz %.r2.fastq.gz
	@$(MAKECALL_PEAR)
	pear -f $< -r $(word 2,$^) -o $@ $(basename $(PEAR_OPTS)) | tee $@
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

pear.stats.long.tsv: $(wildcard *.pear.out)
	for s in $(SAMPLES); do \
	  echo "$(STAT_ORDER)	$$(basename $$(pwd))	$$s	pear	input	$$(grep '^Forward reads file' $$s.*.pear.out | sed 's/.*: //')	$$(grep '^Assembled reads \.' $$s.*.pear.out | sed 's:.* / ::' | sed 's: *(.*::' | sed 's/,//g')"; \
	  echo "$(STAT_ORDER)	$$(basename $$(pwd))	$$s	pear	assembled	$$(grep '^Assembled reads file' $$s.*.pear.out | sed 's/.*: //').gz	$$(grep '^Assembled reads \.' $$s.*.pear.out | sed 's/.*: //' | sed 's: / .*::' | sed 's/,//g')"; \
	  echo "$(STAT_ORDER)	$$(basename $$(pwd))	$$s	pear	unassembled	$$(grep '^Unassembled forward reads file' $$s.*.pear.out | sed 's/.*: //').gz	$$(grep '^Not assembled reads \.' $$s.*.pear.out | sed 's/.*: //' | sed 's: / .*::' | sed 's/,//g')"; \
	done > $@
