# makefile.cutadapt
#
# Library makefile to make running cutadapt simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@lnu.se

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
CUTADAPT_OPTS = -a GATCGGAAGAGCACACGTCTGAACTCCAGTCAC -a ACACTCTTTCCCTACACGACGCTCTTCCGATCT -a CTCGGCATTCCTGCTGAACCGCTCTTCCGATCT -a ACACTCTTTCCCTACACGACGCTCTTCCGATCT

# *** Internal ***

# MAKECALLCUTADAPT is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `cutadapt --version`" > $@.makecall
MAKECALL_PARAMS      = echo "	Called with parameters: $(CUTADAPT_OPTS)" >> $@.makecall
MAKECALL_INFILES     = echo "	Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_CUTADAPT      = $(MAKECALL_VERSION); $(MAKECALL_PARAMS); $(MAKECALL_INFILES)

# *** Targets ***

cutall: $(subst .r1.fastq.gz,.ca.r1.fastq.gz,$(filter-out $(wildcard *.ca.r1.fastq.gz),$(wildcard *.r1.fastq.gz))) $(subst .r2.fastq.gz,.ca.r2.fastq.gz,$(filter-out $(wildcard *.ca.r2.fastq.gz),$(wildcard *.r2.fastq.gz)))

%.ca.r1.fastq.gz: %.r1.fastq.gz
	@$(MAKECALL_CUTADAPT)
	gunzip -c $< | cutadapt $(CUTADAPT_OPTS) - | gzip -c > $@ 2> $@.report
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.ca.r2.fastq.gz: %.r2.fastq.gz
	@$(MAKECALL_CUTADAPT)
	gunzip -c $< | cutadapt $(CUTADAPT_OPTS) - | gzip -c > $@ 2> $@.report
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
