# makefile.deeparg
#
# Library makefile to make running DIAMOND simpler against the deeparg database.
#
# Include the full path of this file in your Makefile and making databases and
# running the aligner can be done via make. See documentation in in
# the biomakefile Git repository: doc/makefile.md and documentation for
# individual targets below.
#
# Author: diego.brambilla@tim.it

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.

#deeparg.py specific macro
# DIAMOND output associate some scores to each match, 
# including the aminoacidic (a.a.) alignement length.
# Defines the desired minimum a.a. alignemnt length threshold that deeparg.py will use
ALENGTH = 37.5

# IMPORTANT: how to download the deeparg database
# 1) $ git clone https://bitbucket.org/gusphdproj/deeparg-ss.git
# then, go to the "database" directory, choose the version (v1 or v2)
# and link the file "features.fasta" into the DIAMOND work directory
# 2) install deeparg, e.g. via conda
# $ conda create -n deeparg_env python=2.7.18
# $ source activate deeparg_env
# $ pip install deeparg==1.0.2
# $ deeparg download_data -o /path/to/local/directory/
# then look for the "features.fasta" file as above.
# More about the deeparg installation on bitbucket:
# https://bitbucket.org/gusphdproj/deeparg-ss/src/master/
# More about the database versions in this thread:
# https://bench.cs.vt.edu/argminer/#/forum/selected_question;id=1582104387832

# Download HTTPS URL for the deeparg.py script, necessary for the downstream analyses
HTTPS = https://gist.github.com/5f3b236bd36acf7a5a7fcf3cff99a56d.git 
# IMPORTANT: after running mirror_deeparg.py, have deeparg.py inside one of the directories listed in the $PATH variable.
# N.B.: the python script "deeparg.py" requires python 3.6*-3.8*

# *** Internal ***

# MAKECALL_DEEPARG is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_DATE     = echo "`date +"%Y-%m-%d %H:%M:%S"`" > $@.makecall
MAKECALL_INFILES     = echo "	Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_DEEPARG = $(MAKECALL_DATE); $(MAKECALL_INFILES)

# *** DeepARG targets ***

# Fetch the deeparg.py script
# Uses git as a prerequisite, if not available you can manually download the file via wget
mirror_deeparg.py:
	git clone $(HTTPS)


# parses DIAMOND m8 matrix to get unique tab-separated hits
# N.B.: need to set OUTFMT=6 
sort_best_m8: $(subst .argdb.m8,.argdb.sort.best.m8, $(wildcard *.argdb.m8))

#filters out DIAMOND m8 matrix to select hits based on alignment length cutoff (input)
deeparg_alength_filter: $(subst .argdb.m8,.argdb.filter.sort.best.m8, $(wildcard *.argdb.m8))

# parses DIMAOND m8 matrixto get an annotated gene list
# N.B.: need to set OUTFMT=6 
sort_argdb_genelist_tsv: $(subst .argdb.m8,.genelist.tsv, $(wildcard *.argdb.m8))


# *** Make rules ***

%.argdb.sort.best.m8: %.argdb.m8
	$(MAKECALL_DEEPARG)
	echo -E "`date +"%Y-%m-%d %H:%M:%S"`: --->sorting $><--"
	sort -u -k1,1 $< | sed 's/|/\t/g' > $@

%.argdb.filter.sort.best.m8: %.argdb.sort.best.m8
	$(MAKECALL_DEEPARG)
	echo -E "`date +"%Y-%m-%d %H:%M:%S"`: --->filtering $><--"
	python deeparg.py $< $(ALENGTH) $@

%.genelist.tsv: %.m8
	$(MAKECALL_DEEPARG)
	echo -E "`date +"%Y-%m-%d %H:%M:%S"`: --->sorting $><--"
	cut -f 1,2 $< | sed 's/|/\t/g' | sort -u -k6,6 - > $@
