###
# Library makefile for NCBI data directories.
#
# Includes targets to mirror data from NCBI (e.g. genomes, NR and RefSeq
# databases) and some other practical things.
#
# Author: daniel.lundin@lnu.se
###

# Set this to suffixes corresponding to the types of files you wish to fetch with some
# of the targets.
ACCEPTED_SUFFIXES = faa.gz

# *** Targets ***

# Get listings, i.e. lists of available files
listings:
	wget -r -x --no-remove-listing --spider ftp://ftp.ncbi.nih.gov

# Mirror parts of available genome databases in various formats.
refseq.assembly_summary.txt:
	wget -O $@ ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/assembly_summary_refseq.txt

archaea.refseq.assembly_summary.txt:
	wget -O $@ ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/archaea/assembly_summary.txt

bacteria.refseq.assembly_summary.txt:
	wget -O $@ ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/assembly_summary.txt

viral.refseq.assembly_summary.txt:
	wget -O $@ ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/viral/assembly_summary.txt

mirror_refseq: refseq.assembly_summary.txt
	for p in $$(awk -F "\t" '$$12=="Complete Genome" && $$11=="latest"{print $$20}' $<); do \
	  echo "--> $$p <--"; \
	  wget -A fna.gz,faa.gz,gbff.gz,gpff.gz --mirror $$p/; \
	done;

mirror_bacteria_gbk:
	wget -A .gbk --mirror  ftp://ftp.ncbi.nih.gov/genomes/Bacteria/

mirror_bacteria_draft_gbk:
	wget -A .gbk --mirror  ftp://ftp.ncbi.nih.gov/genomes/Bacteria_DRAFT/

mirror_assembly_bacteria_gbk:
	wget -A .gbk --mirror  ftp://ftp.ncbi.nih.gov/genomes/ASSEMBLY_BACTERIA

mirror_genbank_genbank_bacteria_gbk:
	wget -A .gbk --mirror  ftp://ftp.ncbi.nih.gov/genbank/genomes/Bacteria

mirror_genbank_genbank_bacteria_draft_gbk:
	wget -A .gbk --mirror  ftp://ftp.ncbi.nih.gov/genbank/genomes/Bacteria_DRAFT/

mirror_viruses_faa:
	wget -A .faa --mirror  ftp://ftp.ncbi.nih.gov/genomes/Viruses/

mirror_viruses_gbk:
	wget -A .gbk --mirror  ftp://ftp.ncbi.nih.gov/genomes/Viruses/

selected_genomes.paths.tsv: selected_genomes.tsv refseq.assembly_summary.txt
	grep -f $< $(word 2,$^) | awk -F "\t" '$$5=="reference genome" || $$5=="representative genome" || $$12=="Complete Genome" {print $$20 "\t" $$8}' > $@

mirror_selected_reference_genomes: selected_genomes.paths.tsv 
	export IFS=$$'\n'; \
	for o in $$(cut -f 2 $<); do \
	  ftp=$$(grep "$$o$$" $< | cut -f 1); \
	  echo "--> $$o: $$ftp <--"; \
	  tp=$$(echo $$ftp | sed 's/ftp:\/\///'); \
	  lp=$$(echo $$o | sed 's/ /_/g'); \
	  wget -A $(ACCEPTED_SUFFIXES) --mirror $$ftp/; \
	  if [ ! -e selected_genomes ]; then mkdir selected_genomes; fi; \
	  ( cd selected_genomes ; ln -f -s ../$$tp $$lp ); \
	done;

# The NR (non-redundant) and RefSeq protein databases

# Fetch the NR protein database, and unpack the tar files.
mirror_nr.blast:
	wget -A "nr.*.tar.gz" --mirror ftp://ftp.ncbi.nih.gov/blast/db
	( cd ftp.ncbi.nih.gov/blast/db; for f in nr.*.tar.gz; do echo "--> $$f <--"; tar xzf $$f; done )

mirror_nr.faa:
	wget --mirror ftp://ftp.ncbi.nih.gov/blast/db/FASTA/nr.gz

mirror_env_nr.faa:
	wget --mirror ftp://ftp.ncbi.nih.gov/blast/db/FASTA/env_nr.gz

# This one only unpacks, what was fetched in mirror_nr.faa. The latter hence
# has to be run first.
nr.faa: ftp.ncbi.nih.gov/blast/db/FASTA/nr.gz 
	gunzip -c $< | awk '/^>/ {printf("\n%s\n",$$0);next; } { printf("%s",$$0);}  END {printf("\n");}' | sed '/^>/! { s/-//g }' > $@

env_nr.faa: ftp.ncbi.nih.gov/blast/db/FASTA/env_nr.gz 
	gunzip -c $< | awk '/^>/ {printf("\n%s\n",$$0);next; } { printf("%s",$$0);}  END {printf("\n");}' | sed '/^>/! { s/-//g }' > $@

# Fetch the RefSeq protein database, and unpack the tar files.
mirror_refseq_protein.blast:
	wget -A "refseq_protein.*.tar.gz" --mirror ftp://ftp.ncbi.nih.gov/blast/db
	( cd ftp.ncbi.nih.gov/blast/db; for f in refseq_protein.*.tar.gz; do echo "--> gunzipping $$f <--"; tar xzf $$f; done )

# Extract sequences from the RefSeq protein database fetched by
# mirror_refseq_protein.blast.  As far as I know there's no fasta file for this
# available at NCBI, like there is for NR.
refseq_protein.faa: $(wildcard ftp.ncbi.nih.gov/blast/db/refseq_protein*)
	blastdbcmd -db ftp.ncbi.nih.gov/blast/db/refseq_protein -entry all -dbtype prot -out $@

mirror_refseq_rna.blast:
	wget -A "refseq_rna.*.tar.gz" --mirror ftp://ftp.ncbi.nih.gov/blast/db
	( cd ftp.ncbi.nih.gov/blast/db; for f in refseq_rna.*.tar.gz; do echo "--> gunzipping $$f <--"; tar xzf $$f; done )

refseq_rna.fna:
	blastdbcmd -db ftp.ncbi.nih.gov/blast/db/refseq_rna -entry all -dbtype nucl -out $@

# The taxonomy database
taxdump.tar.gz:
	wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz

nodes.dmp: taxdump.tar.gz
	tar xfz $< $@

names.dmp: taxdump.tar.gz
	tar xfz $< $@

# The below target requires that the taxdata2taxflat program is installed
# somewhere in your PATH. It's available from GitHub:
#
#   https://github.com/erikrikarddaniel/taxdata2taxflat
taxflat.tsv: nodes.dmp names.dmp
	taxdata2taxflat --verbose $^ > $@

# The nucleotide blast database
ncbi_nt:
	wget "ftp://ftp.ncbi.nlm.nih.gov/blast/db/nt.*.tar.gz"
