# makefile.bowtie2
#
# Library makefile to make running bowtie2 simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@lnu.se

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
BOWTIE_BUILD_OPTS =
BOWTIE_ALIGN_OPTS =

BOWTIE_INDEX = NEED TO BE SET TO THE NAME OF YOUR INDEX, WITHOUT ".bowtie2index"

# The below directory will be searched for the SILVA_CURRENT_Parc_tax_silva and
# SILVA_CURRENT_Ref_tax_silva bowtie2 index files for the Parc and Ref
# databases respectively. See makefile.silva for how to download and construct
# them.
SILVA_DIRECTORY = FOR SILVA MAPPINGS: NEED TO BE SET TO DIRECTORY CONTAINING SILVA FILES

# *** Internal ***

# This is a set of macros that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_BOWTIE2_VERSION      	 = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with $(bowtie2 --version|grep 'bowtie2.*version'|sed 's/.*version //')" > $@.makecall
MAKECALL_BOWTIE2_ALIGN_PARAMS 	 = echo "	Called with parameters: $(BOWTIE_ALIGN_OPTS)" >> $@.makecall
MAKECALL_BOWTIE2_BUILD_PARAMS 	 = echo "	Called with parameters: $(BOWTIE_BUILD_OPTS)" >> $@.makecall
MAKECALL_BOWTIE2_INFILES      	 = echo "	Input files: $^ (`ls -lL $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_BOWTIE2_DB	      	 = echo "  Database files: $$(ls -lL $(BOWTIE_INDEX).*)" >> $@.makecall
MAKECALL_BOWTIE2_SILVAPARCDB  	 = echo "  Database files: $$(ls -lL $(SILVA_DIRECTORY)/SILVA_CURRENT_Parc_tax_silva.u2t.*)" >> $@.makecall
MAKECALL_BOWTIE2_SILVAREFDB   	 = echo "  Database files: $$(ls -lL $(SILVA_DIRECTORY)/SILVA_CURRENT_Ref_tax_silva.u2t.*)" >> $@.makecall
MAKECALL_BOWTIE2_ALIGN        	 = $(MAKECALL_BOWTIE2_VERSION); $(MAKECALL_BOWTIE2_ALIGN_PARAMS); $(MAKECALL_BOWTIE2_INFILES)
MAKECALL_BOWTIE2_ALIGN        	 = $(MAKECALL_BOWTIE2_VERSION); $(MAKECALL_BOWTIE2_BUILD_PARAMS); $(MAKECALL_BOWTIE2_INFILES); $(MAKECALL_BOWTIE2_DB)
MAKECALL_BOWTIE2_SILVAPARC_ALIGN = $(MAKECALL_BOWTIE2_VERSION); $(MAKECALL_BOWTIE2_BUILD_PARAMS); $(MAKECALL_BOWTIE2_INFILES); $(MAKECALL_BOWTIE2_SILVAPARCDB)
MAKECALL_BOWTIE2_SILVAREF_ALIGN  = $(MAKECALL_BOWTIE2_VERSION); $(MAKECALL_BOWTIE2_BUILD_PARAMS); $(MAKECALL_BOWTIE2_INFILES); $(MAKECALL_BOWTIE2_SILVAREFDB)
MAKECALL_BOWTIE2_BUILD        	 = $(MAKECALL_BOWTIE2_VERSION); $(MAKECALL_BOWTIE2_BUILD_PARAMS); $(MAKECALL_BOWTIE2_INFILES)

# *** Targets ***

all_pe_sams: $(subst .r1.fastq.gz,.pe.bowtie2.sam,$(wildcard *.r1.fastq.gz))

all_pe_sorted_bams: $(subst .r1.fastq.gz,.pe.bowtie2.sorted.bam,$(wildcard *.r1.fastq.gz))

all_pe_sams.gz: $(subst .r1.fastq.gz,.pe.bowtie2.sam.gz,$(wildcard *.r1.fastq.gz))

all_se_sams: $(subst .r1.fastq.gz,.se.bowtie2.sam,$(wildcard *.r1.fastq.gz))

all_se_sams.gz: $(subst .fastq.gz,.se.bowtie2.sam.gz,$(wildcard *.fastq.gz))

all_interleaved_sorted_bams: $(subst .int.fastq.gz,.int.bowtie2.sorted.bam,$(wildcard *.int.fastq.gz))

%.pe.bowtie2.sam: %.r1.fastq.gz %.r2.fastq.gz
	@$(MAKECALL_BOWTIE2_ALIGN)
	bowtie2 $(BOWTIE_ALIGN_OPTS) -x $(BOWTIE_INDEX) -1 $(word 1,$^) -2 $(word 2,$^) > $@ 2> $@.err
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.pe.bowtie2.sorted.bam: %.r1.fastq.gz %.r2.fastq.gz
	@$(MAKECALL_BOWTIE2_ALIGN)
	bowtie2 $(BOWTIE_ALIGN_OPTS) -x $(BOWTIE_INDEX) -1 $(word 1,$^) -2 $(word 2,$^) 2> $@.err | samtools view -Sb | samtools sort > $@
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.pe.bowtie2.sam.gz: %.r1.fastq.gz %.r2.fastq.gz
	@$(MAKECALL_BOWTIE2_ALIGN)
	bowtie2 $(BOWTIE_ALIGN_OPTS) -x $(BOWTIE_INDEX) -1 $(word 1,$^) -2 $(word 2,$^) 2> $(basename $@).err | gzip -c > $@ 
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.se.bowtie2.sam: %.r1.fastq.gz
	@$(MAKECALL_BOWTIE2_ALIGN)
	bowtie2 $(BOWTIE_ALIGN_OPTS) -x $(BOWTIE_INDEX) -U $< > $@ 2> $@.err
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.se.bowtie2.sam.gz: %.fastq.gz
	@$(MAKECALL_BOWTIE2_ALIGN)
	bowtie2 $(BOWTIE_ALIGN_OPTS) -x $(BOWTIE_INDEX) -U $< 2> $@.err | gzip -c > $@
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
	
%.int.bowtie2.sorted.bam: %.int.fastq.gz
	@$(MAKECALL_BOWTIE2_ALIGN)
	bowtie2 $(BOWTIE_ALIGN_OPTS) -x $(BOWTIE_INDEX) --interleaved $(word 1,$^) 2> $@.err | samtools view -Sb | samtools sort > $@
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

# SILVA mapping targets
all_silvaparcs: $(subst .r1.fastq.gz,.pe.bowtie2-silvaparc.sam.gz,$(wildcard *.r1.fastq.gz))

all_silvarefs: $(subst .r1.fastq.gz,.pe.bowtie2-silvaref.sam.gz,$(wildcard *.r1.fastq.gz))

%.pe.bowtie2-silvaparc.sam.gz: %.r1.fastq.gz %.r2.fastq.gz
	@$(MAKECALL_BOWTIE2_SILVAPARC_ALIGN)
	bowtie2 $(BOWTIE_ALIGN_OPTS) -x $(SILVA_DIRECTORY)/SILVA_CURRENT_Parc_tax_silva.u2t -1 $(word 1,$^) -2 $(word 2,$^) 2> $(basename $@).err | gzip -c > $@ 
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

%.pe.bowtie2-silvaref.sam.gz: %.r1.fastq.gz %.r2.fastq.gz
	@$(MAKECALL_BOWTIE2_SILVAREF_ALIGN)
	bowtie2 $(BOWTIE_ALIGN_OPTS) -x $(SILVA_DIRECTORY)/SILVA_CURRENT_Ref_tax_silva.u2t -1 $(word 1,$^) -2 $(word 2,$^) 2> $(basename $@).err | gzip -c > $@ 
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall

# Indices
all_bowtie2indeces: $(subst .fna,.bowtie2index,$(wildcard *.fna))

%.bowtie2index: %.fna
	@$(MAKECALL_BOWTIE2_BUILD)
	bowtie2-build $(BOWTIE_INDEX_OPTS) -f $< $(basename $@) | tee $@.err 2>&1
	touch $@
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
