# makefile.bmge
#
# Library makefile to make running the BMGE alignment analysis program
# (Criscuolo & Gribaldo, BMC Evol. Biol., 2010) simpler.
#
# The program evaluates positions in multiple protein alignments with the
# purpose of detecting trustworthy columns. It can be tuned in various ways to
# be more or less conservative. In this file there is currently support for
# default options (the %.bmge.alnfaa target) as well as a selection of BLOSUM
# options. The latter is best used via the %.bmge.charsets target that runs BMGE
# for all BLOSUM settings and then constructs a NEXUS character set that can be
# included in e.g. seaview files. It also outputs alnfaa files, i.e. multiple
# alignment fasta files, with the selected positions.
#
# All targets are dependent on a multiple alignment fasta file (.alnfaa).
#
# Include the full path of this file in your Makefile ...
#
# Author: erik.rikard.daniel@gmail.com

# Default settings
%.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA

# Lots of targets for various BMGE calls followed by output of a NEXUS character
# sets clause for inclusion in e.g. seaview files.
%.bmge.charsets: %.BLOSUM30.bmge.charset %.BLOSUM35.bmge.charset %.BLOSUM40.bmge.charset %.BLOSUM45.bmge.charset %.BLOSUM50.bmge.charset %.BLOSUM55.bmge.charset %.BLOSUM60.bmge.charset %.BLOSUM62.bmge.charset %.BLOSUM65.bmge.charset %.BLOSUM70.bmge.charset %.BLOSUM75.bmge.charset %.BLOSUM80.bmge.charset %.BLOSUM85.bmge.charset %.BLOSUM90.bmge.charset %.BLOSUM95.bmge.charset
	cat $^ > $@

%.bmge.charset: %.bmge.html %.bmge.alnfaa
	n=`echo $@ | sed 's/^.*\.\([^.]\+\).bmge.charset/\1/'`; \
	grep 'selected:' $< | sed "s/ *selected: */  CHARSET '$$n' =/" | sed 's/$$/;/' > $@

%.BLOSUM30.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM30

%.BLOSUM35.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM35

%.BLOSUM40.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM40

%.BLOSUM45.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM45

%.BLOSUM50.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM50

%.BLOSUM55.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM55

%.BLOSUM60.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM60

%.BLOSUM62.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM62

%.BLOSUM65.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM65

%.BLOSUM70.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM70

%.BLOSUM75.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM75

%.BLOSUM80.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM80

%.BLOSUM85.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM85

%.BLOSUM90.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM90

%.BLOSUM95.bmge.html: %.alnfaa
	bmge -i $< -oh $@ -t AA -m BLOSUM95

.SECONDARY:

%.BLOSUM30.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM30

%.BLOSUM35.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM35

%.BLOSUM40.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM40

%.BLOSUM45.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM45

%.BLOSUM50.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM50

%.BLOSUM55.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM55

%.BLOSUM60.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM60

%.BLOSUM62.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM62

%.BLOSUM65.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM65

%.BLOSUM70.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM70

%.BLOSUM75.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM75

%.BLOSUM80.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM80

%.BLOSUM85.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM85

%.BLOSUM90.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM90

%.BLOSUM95.bmge.alnfaa: %.alnfaa
	bmge -i $< -of $@ -t AA -m BLOSUM95
