# makefile.pear
#
# Library makefile to make running the PEAR program simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: erik.rikard.daniel@gmail.com

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
PEAR_OPTS =

# *** Internal ***

# MAKECALLPEAR is a macro that defines what will be output to the .makecall
# file, the file that records versions, file stamps, parameters etc.
#
# *Don't redefine!*
MAKECALL_VERSION     = echo "`date +"%Y%m%d %H:%M:%S"`: $@ was made with `pear --version`" > $@.makecall
MAKECALL_PARAMS      = echo "	Called with parameters: $(PEAR_OPTS)" >> $@.makecall
MAKECALL_INFILES     = echo "	Input files: $^ (`ls -l $^|tr '\n' ','`)" >> $@.makecall
MAKECALL_PEAR      = $(MAKECALL_VERSION); $(MAKECALL_PARAMS); $(MAKECALL_INFILES)

# *** Targets ***

fastq.gzs2pears: $(subst .r1.fastq.gz,.pear.out,$(wildcard *.r1.fastq.gz))

%.pear.out: %.r1.fastq.gz %.r2.fastq.gz
	@$(MAKECALL_PEAR)
	pear -f $< -r $(word 2,$^) -o $@ $(basename $(PEAR_OPTS)) | tee $@
	@echo "`date +"%Y%m%d %H:%M:%S"`: DONE" >> $@.makecall
