# makefile.gtdb
#
# Library makefile to make fetching data from GTDB simpler.
#
# Include the full path of this file in your Makefile ...
#
# Author: daniel.lundin@lnu.se, daniel.lundin@dbb.su.se

SHELL := /bin/bash

# *** Parameters ***

# Override in your Makefile by setting a parameter *after* the row that
# includes this file, see documentation in doc/makefile.md.
#
GTDB_LATEST_URL = https://data.ace.uq.edu.au/public/gtdb/data/releases/latest

# MOVE to makefile.gtdbtk
GTDBTK_OPTIONS =

# *** Internal ***

# *** Targets ***

# MOVE the GTDBtk stuff to makefile.gtdbtk
# Fetch data
gtdbtk_current_data.tar.gz:
	wget https://data.ace.uq.edu.au/public/gtdbtk/release_$(GTDBTK_RELEASE)/gtdbtk.r$(GTDBTK_RELEASE)_data.tar.gz
	ln -s gtdbtk.r$(GTDBTK_RELEASE)_data.tar.gz $@

# Run the standard workflow on all genomes in "genome_bins"
gtdbtk_classify_wf.d: $(wildcard genome_bins/*.fna)
	gtdbtk classify_wf --genome_dir $(dir $<) --out_dir $@ $(GTDBTK_OPTIONS)

taxonomies: ar122_taxonomy.tsv bac120_taxonomy.tsv

metadata: ar122_metadata.tsv bac120_metadata.tsv

trees: ar122.tree bac120.tree ar122.sp_labels.tree bac120.sp_labels.tree

# Download data (easier to do with the script included in the distribution)
ar122_taxonomy.tsv:
	wget $(GTDB_LATEST_URL)/$@

ar122_metadata.tsv:
	wget $(GTDB_LATEST_URL)/$@

ar122.tree:
	wget $(GTDB_LATEST_URL)/$@

ar122.sp_labels.tree:
	wget $(GTDB_LATEST_URL)/$@

bac120_taxonomy.tsv:
	wget $(GTDB_LATEST_URL)/$@

bac120_metadata.tsv:
	wget $(GTDB_LATEST_URL)/$@

bac120.tree:
	wget $(GTDB_LATEST_URL)/$@

bac120.sp_labels.tree:
	wget $(GTDB_LATEST_URL)/$@

ncbi_genome_accnos.tsv: arc_metadata.tsv bac_metadata.tsv
	cut -f 1 $^ | grep -v 'accession' | sed 's/^[A-Z][A-Z]_//' > $@

# Splits the ; separated hierarchy in the original files to a tab separated
%.split.tsv: %.tsv
	sed 's/\td__/\t/' $< | sed 's/;[a-z]__/\t/g' > $@

# Makes a file with unique species lineages, by removing the genome accno and finding the unique
%.uniqlineages.tsv: %.genomes.split.tsv
	cut -f 2-20 $< | sort -u > $@

# Just playing around...
arc_bac.phyla.newick: arc_taxonomy.phyla.newick bac_taxonomy.phyla.newick
	echo "($$(sed 's/;//' $<),$$(sed 's/;//' $(word 2,$^)));" > $@
%.phyla.newick: %.uniqlineages.tsv
	echo "($$(cut -f 2 $< | sort -u | tr '\n' ',' | sed 's/,$$//' ))$$(cut -f 1 $< | sort -u | tr '\n' ' ');" > $@
